version: '3'

services:
  app:
    build:
      context: ./api
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 node index.js
    restart: always
    networks:
      - challange_network
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"

  proxy:
    build:
      context: ./proxy
    container_name: nginx
    depends_on:
      - app
    networks:
      - challange_network
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challange_network

networks:
  challange_network:
    driver: bridge
    name: challange_network